dist: bionic

language: ruby

rvm:
  - 2.7.2

env:
  jobs:
    - RAILS_VERSION="~> 4.2.0"

addons:
  postgresql: "13"
  apt:
    packages:
    - postgresql-13

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '1.17.3' #downgrade bundler for rails4
  - bundle install

script:
  - rake compile test
